//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Personel.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_calisma_yeri
    {
        public int calisma_id { get; set; }
        public string calisma_yeri_adi { get; set; }
        public int bolge_id { get; set; }
        public int firma_id { get; set; }
    
        public virtual tbl_bolgeler tbl_bolgeler { get; set; }
        public virtual tbl_firmalar tbl_firmalar { get; set; }
    }
}
