//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Personel.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_bolgeler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_bolgeler()
        {
            this.tbl_gorevler = new HashSet<tbl_gorevler>();
            this.tbl_degerlendirme = new HashSet<tbl_degerlendirme>();
            this.tbl_calisma_yeri = new HashSet<tbl_calisma_yeri>();
        }
    
        public int bolge_id { get; set; }
        public string bolge_adi { get; set; }
        public int firma_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_gorevler> tbl_gorevler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_degerlendirme> tbl_degerlendirme { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_calisma_yeri> tbl_calisma_yeri { get; set; }
        public virtual tbl_firmalar tbl_firmalar { get; set; }
    }
}
