//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Personel.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_sgk_kayit_hareketleri
    {
        public int sgk_hareket_id { get; set; }
        public int personel_id { get; set; }
        public int sgk_kayit_yeri_id { get; set; }
        public System.DateTime giris_tarihi { get; set; }
        public Nullable<System.DateTime> cikis_tarihi { get; set; }
    
        public virtual tbl_personel tbl_personel { get; set; }
        public virtual tbl_sgk_kayit_yeri tbl_sgk_kayit_yeri { get; set; }
    }
}
