//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Personel.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_personel_ozluk
    {
        public int ozluk_id { get; set; }
        public int personel_id { get; set; }
        public string durum { get; set; }
        public string dosya_yolu { get; set; }
        public string dosya_adi { get; set; }
        public Nullable<int> belge_id { get; set; }
    
        public virtual tbl_ozluk_belgeler tbl_ozluk_belgeler { get; set; }
        public virtual tbl_personel tbl_personel { get; set; }
    }
}
