//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Personel.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_degerlendirme
    {
        public int degerlendirme_id { get; set; }
        public string donem { get; set; }
        public int personel_id { get; set; }
        public int gorev_id { get; set; }
        public int puan { get; set; }
        public int bolge_id { get; set; }
        public int firma_id { get; set; }
        public string aciklama { get; set; }
    
        public virtual tbl_bolgeler tbl_bolgeler { get; set; }
        public virtual tbl_firmalar tbl_firmalar { get; set; }
        public virtual tbl_gorevler tbl_gorevler { get; set; }
        public virtual tbl_personel tbl_personel { get; set; }
    }
}
