//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Personel.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_kullanici
    {
        public int kullanici_id { get; set; }
        public string kullanici_adi { get; set; }
        public string adi { get; set; }
        public string soyadi { get; set; }
        public string sifre { get; set; }
        public string mail { get; set; }
        public Nullable<int> firma_id { get; set; }
        public string yetki_grubu { get; set; }
    
        public virtual tbl_firmalar tbl_firmalar { get; set; }
    }
}
