//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Personel.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.Web.Mvc;

    public partial class tbl_personel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_personel()
        {
            this.tbl_degerlendirme = new HashSet<tbl_degerlendirme>();
            this.tbl_izinler = new HashSet<tbl_izinler>();
            this.tbl_sgk_kayit_hareketleri = new HashSet<tbl_sgk_kayit_hareketleri>();
            this.tbl_personel_ozluk = new HashSet<tbl_personel_ozluk>();

            this.SgkKayitYeriList = new List<SelectListItem>();
        }
    
        public int personel_id { get; set; }
        public string personel_kodu { get; set; }
        public string personel_adi { get; set; }
        public string personel_soyadi { get; set; }
        public Nullable<int> sgk_kayit_yeri_id { get; set; }
        public System.DateTime ise_giris_tarihi { get; set; }
        public Nullable<System.DateTime> isten_cikis_tarihi { get; set; }
        public Nullable<int> firma_id { get; set; }
        public string durum { get; set; }
        public string cinsiyet { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_degerlendirme> tbl_degerlendirme { get; set; }
        public virtual tbl_firmalar tbl_firmalar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_izinler> tbl_izinler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_sgk_kayit_hareketleri> tbl_sgk_kayit_hareketleri { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_personel_ozluk> tbl_personel_ozluk { get; set; }

        public List<SelectListItem> FirmaList { get; set; }
        public List<SelectListItem> SgkKayitYeriList { get; set; }
    }
}
